#07
name: Terraform Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  security-events: write  # Required for uploading SARIF results

env:
  AWS_REGION: ${{ secrets.AWS_REGION }} 
  TF_STATE_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
  TF_STATE_KEY: ${{ secrets.AWS_BUCKET_KEY_NAME }}

jobs:
  terraform:
    name: Deploy Terraform on AWS
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 'AWS'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: terraform-github-actions

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.2.5'
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" -backend-config="key=${{ env.TF_STATE_KEY }}" -backend-config="region=${{ env.AWS_REGION }}"
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      # ✅ Run Tenable scan and generate SARIF report
      - name: Scan with Tenable Cloud Security
        uses: tenable/cloud-security-actions/iac/scan@v1
        with:
          api-token: ${{ secrets.TENABLE_API_TOKEN }}
          api-url: https://us2.app.ermetic.com
          paths: AWS
          output-file-formats: sarif
          output-file-name: tenable-results

      # ✅ Debug: Confirm SARIF file exists and check its permissions
      - name: Check SARIF file owner and permissions
        run: ls -lah /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/tenable-results.sarif

      # ✅ Copy SARIF file to a writable directory and fix permissions
      - name: Copy SARIF file to /tmp and fix permissions
        run: |
          sudo cp /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/tenable-results.sarif /tmp/tenable-results.sarif
          sudo chmod 644 /tmp/tenable-results.sarif
          ls -l /tmp/tenable-results.sarif

      # ✅ Normalize SARIF file paths before uploading
      - name: Fix SARIF file paths
        run: |
          jq '.runs[].results[].locations[].physicalLocation.artifactLocation.uri |= sub("https://[^/]*/"; "")' \
            /tmp/tenable-results.sarif > /tmp/tenable-results-fixed.sarif
          mv /tmp/tenable-results-fixed.sarif /tmp/tenable-results.sarif
          ls -l /tmp/tenable-results.sarif
      
      - name: Upload SARIF report to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: /tmp/tenable-results.sarif
          token: ${{ secrets.GITHUB_TOKEN }}  # Use built-in GitHub token

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
      
      - name: Pull remote terraform state
        run: terraform state pull > terraform.tfstate
        shell: bash

      - name: Sync with Tenable Cloud Security
        uses: tenable/cloud-security-actions/iac/sync/terraform@v1
        with:
          api-token: ${{ secrets.TENABLE_API_TOKEN }}
          api-url: https://us2.app.ermetic.com
          path: AWS
          state-file-path: AWS/terraform.tfstate
